
#include "fbt_sec_syscalls.h"

//const authorize_syscl_fptr_t authorize_syscl_table[] = {
authorize_syscl_fptr_t authorize_syscl_table[] = {
    allow_syscall, // __NR_restart_syscall      0
    allow_syscall, // __NR_exit		  1
    allow_syscall, // __NR_fork		  2
    allow_syscall, // __NR_read		  3
    allow_syscall, // __NR_write		  4     // short_strings
    check_open_syscall, // __NR_open		  5
    allow_syscall, // __NR_close		  6
    allow_syscall, // __NR_waitpid		  7
    check_open_syscall, // __NR_creat		  8
    allow_syscall, // __NR_link		  9
    allow_syscall, // __NR_unlink		 10
    fbt_check_execve, // __NR_execve		 11
    allow_syscall, // __NR_chdir		 12
    allow_syscall, // __NR_time		 13
    allow_syscall, // __NR_mknod		 14
    allow_syscall, // __NR_chmod		 15
    allow_syscall, // __NR_lchown		 16
    allow_syscall, // __NR_break		 17
    allow_syscall, // __NR_oldstat		 18
    allow_syscall, // __NR_lseek		 19
    allow_syscall, // __NR_getpid		 20
    allow_syscall, // __NR_mount		 21
    allow_syscall, // __NR_umount		 22
    allow_syscall, // __NR_setuid		 23
    allow_syscall, // __NR_getuid		 24
    allow_syscall, // __NR_stime		 25
    deny_syscall, // __NR_ptrace		 26
    allow_syscall, // __NR_alarm		 27
    allow_syscall, // __NR_oldfstat		 28
    allow_syscall, // __NR_pause		 29
    allow_syscall, // __NR_utime		 30
    allow_syscall, // __NR_stty		 31
    allow_syscall, // __NR_gtty		 32
    allow_syscall, // __NR_access		 33
    allow_syscall, // __NR_nice		 34
    allow_syscall, // __NR_ftime		 35
    allow_syscall, // __NR_sync		 36
    allow_syscall, // __NR_kill		 37
    allow_syscall, // __NR_rename		 38
    allow_syscall, // __NR_mkdir		 39
    allow_syscall, // __NR_rmdir		 40
    allow_syscall, // __NR_dup		 41
    allow_syscall, // __NR_pipe		 42
    allow_syscall, // __NR_times		 43
    allow_syscall, // __NR_prof		 44
    allow_syscall, // __NR_brk		 45
    allow_syscall, // __NR_setgid		 46
    allow_syscall, // __NR_getgid		 47
    allow_syscall, // __NR_signal		 48
    allow_syscall, // __NR_geteuid		 49
    allow_syscall, // __NR_getegid		 50
    allow_syscall, // __NR_acct		 51
    allow_syscall, // __NR_umount2		 52
    allow_syscall, // __NR_lock		 53
    allow_syscall, // __NR_ioctl		 54
    allow_syscall, // __NR_fcntl		 55
    allow_syscall, // __NR_mpx		 56
    allow_syscall, // __NR_setpgid		 57
    allow_syscall, // __NR_ulimit		 58
    allow_syscall, // __NR_oldolduname	 59
    allow_syscall, // __NR_umask		 60
    allow_syscall, // __NR_chroot		 61
    allow_syscall, // __NR_ustat		 62
    allow_syscall, // __NR_dup2		 63
    allow_syscall, // __NR_getppid		 64
    allow_syscall, // __NR_getpgrp		 65
    allow_syscall, // __NR_setsid		 66
    allow_syscall, // __NR_sigaction		 67
    allow_syscall, // __NR_sgetmask		 68
    allow_syscall, // __NR_ssetmask		 69
    allow_syscall, // __NR_setreuid		 70
    allow_syscall, // __NR_setregid		 71
    allow_syscall, // __NR_sigsuspend		 72
    allow_syscall, // __NR_sigpending		 73
    allow_syscall, // __NR_sethostname	 74
    allow_syscall, // __NR_setrlimit		 75
    allow_syscall, // __NR_getrlimit		 76   /* Back compatible 2Gig limited rlimit */
    allow_syscall, // __NR_getrusage		 77
    allow_syscall, // __NR_gettimeofday	 78
    allow_syscall, // __NR_settimeofday	 79
    allow_syscall, // __NR_getgroups		 80
    allow_syscall, // __NR_setgroups		 81
    allow_syscall, // __NR_select		 82
    allow_syscall, // __NR_symlink		 83
    allow_syscall, // __NR_oldlstat		 84
    allow_syscall, // __NR_readlink		 85
    allow_syscall, // __NR_uselib		 86
    allow_syscall, // __NR_swapon		 87
    allow_syscall, // __NR_reboot		 88
    allow_syscall, // __NR_readdir		 89
    intercept_mmap, // __NR_mmap		 90
    allow_syscall, // __NR_munmap		 91
    allow_syscall, // __NR_truncate		 92
    allow_syscall, // __NR_ftruncate		 93
    allow_syscall, // __NR_fchmod		 94
    allow_syscall, // __NR_fchown		 95
    allow_syscall, // __NR_getpriority	 96
    allow_syscall, // __NR_setpriority	 97
    allow_syscall, // __NR_profil		 98
    allow_syscall, // __NR_statfs		 99
    allow_syscall, // __NR_fstatfs		100
    allow_syscall, // __NR_ioperm		101
    allow_syscall, // __NR_socketcall		102
    allow_syscall, // __NR_syslog		103
    allow_syscall, // __NR_setitimer		104
    allow_syscall, // __NR_getitimer		105
    allow_syscall, // __NR_stat		106
    allow_syscall, // __NR_lstat		107
    allow_syscall, // __NR_fstat		108
    allow_syscall, // __NR_olduname		109
    allow_syscall, // __NR_iopl		110
    allow_syscall, // __NR_vhangup		111
    allow_syscall, // __NR_idle		112
    allow_syscall, // __NR_vm86old		113
    allow_syscall, // __NR_wait4		114
    allow_syscall, // __NR_swapoff		115
    allow_syscall, // __NR_sysinfo		116
    allow_syscall, // __NR_ipc		117
    allow_syscall, // __NR_fsync		118
    allow_syscall, // __NR_sigreturn		119
    allow_syscall, // __NR_clone		120
    allow_syscall, // __NR_setdomainname	121
    allow_syscall, // __NR_uname		122
    allow_syscall, // __NR_modify_ldt		123
    allow_syscall, // __NR_adjtimex		124
    intercept_mprotect, // __NR_mprotect		125
    allow_syscall, // __NR_sigprocmask	126
    allow_syscall, // __NR_create_module	127
    allow_syscall, // __NR_init_module	128
    allow_syscall, // __NR_delete_module	129
    allow_syscall, // __NR_get_kernel_syms	130
    allow_syscall, // __NR_quotactl		131
    allow_syscall, // __NR_getpgid		132
    allow_syscall, // __NR_fchdir		133
    allow_syscall, // __NR_bdflush		134
    allow_syscall, // __NR_sysfs		135
    allow_syscall, // __NR_personality	136
    allow_syscall, // __NR_afs_syscall	137 /* Syscall for Andrew File System */
    allow_syscall, // __NR_setfsuid		138
    allow_syscall, // __NR_setfsgid		139
    allow_syscall, // __NR__llseek		140
    allow_syscall, // __NR_getdents		141
    allow_syscall, // __NR__newselect		142
    allow_syscall, // __NR_flock		143
    allow_syscall, // __NR_msync		144
    allow_syscall, // __NR_readv		145
    allow_syscall, // __NR_writev		146
    allow_syscall, // __NR_getsid		147
    allow_syscall, // __NR_fdatasync		148
    allow_syscall, // __NR__sysctl		149
    allow_syscall, // __NR_mlock		150
    allow_syscall, // __NR_munlock		151
    allow_syscall, // __NR_mlockall		152
    allow_syscall, // __NR_munlockall		153
    allow_syscall, // __NR_sched_setparam		154
    allow_syscall, // __NR_sched_getparam		155
    allow_syscall, // __NR_sched_setscheduler		156
    allow_syscall, // __NR_sched_getscheduler		157
    allow_syscall, // __NR_sched_yield		158
    allow_syscall, // __NR_sched_get_priority_max	159
    allow_syscall, // __NR_sched_get_priority_min	160
    allow_syscall, // __NR_sched_rr_get_interval	161
    allow_syscall, // __NR_nanosleep		162
    allow_syscall, // __NR_mremap		163
    allow_syscall, // __NR_setresuid		164
    allow_syscall, // __NR_getresuid		165
    allow_syscall, // __NR_vm86		166
    allow_syscall, // __NR_query_module	167
    allow_syscall, // __NR_poll		168
    allow_syscall, // __NR_nfsservctl		169
    allow_syscall, // __NR_setresgid		170
    allow_syscall, // __NR_getresgid		171
    allow_syscall, // __NR_prctl              172
    allow_syscall, // __NR_rt_sigreturn	173
    allow_syscall, // __NR_rt_sigaction	174
    allow_syscall, // __NR_rt_sigprocmask	175
    allow_syscall, // __NR_rt_sigpending	176
    allow_syscall, // __NR_rt_sigtimedwait	177
    allow_syscall, // __NR_rt_sigqueueinfo	178
    allow_syscall, // __NR_rt_sigsuspend	179
    allow_syscall, // __NR_pread64		180
    allow_syscall, // __NR_pwrite64		181
    allow_syscall, // __NR_chown		182
    allow_syscall, // __NR_getcwd		183
    allow_syscall, // __NR_capget		184
    allow_syscall, // __NR_capset		185
    allow_syscall, // __NR_sigaltstack	186
    allow_syscall, // __NR_sendfile		187
    allow_syscall, // __NR_getpmsg		188	/* some people actually want streams */
    allow_syscall, // __NR_putpmsg		189	/* some people actually want streams */
    allow_syscall, // __NR_vfork		190
    allow_syscall, // __NR_ugetrlimit		191	/* SuS compliant getrlimit */
    allow_syscall, // __NR_mmap2		192
    allow_syscall, // __NR_truncate64		193
    allow_syscall, // __NR_ftruncate64	194
    allow_syscall, // __NR_stat64		195
    allow_syscall, // __NR_lstat64		196
    allow_syscall, // __NR_fstat64		197
    allow_syscall, // __NR_lchown32		198
    allow_syscall, // __NR_getuid32		199
    allow_syscall, // __NR_getgid32		200
    allow_syscall, // __NR_geteuid32		201
    allow_syscall, // __NR_getegid32		202
    allow_syscall, // __NR_setreuid32		203
    allow_syscall, // __NR_setregid32		204
    allow_syscall, // __NR_getgroups32	205
    allow_syscall, // __NR_setgroups32	206
    allow_syscall, // __NR_fchown32		207
    allow_syscall, // __NR_setresuid32	208
    allow_syscall, // __NR_getresuid32	209
    allow_syscall, // __NR_setresgid32	210
    allow_syscall, // __NR_getresgid32	211
    allow_syscall, // __NR_chown32		212
    allow_syscall, // __NR_setuid32		213
    allow_syscall, // __NR_setgid32		214
    allow_syscall, // __NR_setfsuid32		215
    allow_syscall, // __NR_setfsgid32		216
    allow_syscall, // __NR_pivot_root		217
    allow_syscall, // __NR_mincore		218
    allow_syscall, // __NR_madvise		219
    allow_syscall, // __NR_getdents64		220
    allow_syscall, // __NR_fcntl64		221
    deny_syscall, // 222, unused?
    deny_syscall, // 223, unused.
    allow_syscall, // __NR_gettid		224
    allow_syscall, // __NR_readahead		225
    allow_syscall, // __NR_setxattr		226
    allow_syscall, // __NR_lsetxattr		227
    allow_syscall, // __NR_fsetxattr		228
    allow_syscall, // __NR_getxattr		229
    allow_syscall, // __NR_lgetxattr		230
    allow_syscall, // __NR_fgetxattr		231
    allow_syscall, // __NR_listxattr		232
    allow_syscall, // __NR_llistxattr		233
    allow_syscall, // __NR_flistxattr		234
    allow_syscall, // __NR_removexattr	235
    allow_syscall, // __NR_lremovexattr	236
    allow_syscall, // __NR_fremovexattr	237
    allow_syscall, // __NR_tkill		238
    allow_syscall, // __NR_sendfile64		239
    allow_syscall, // __NR_futex		240
    allow_syscall, // __NR_sched_setaffinity	241
    allow_syscall, // __NR_sched_getaffinity	242
    allow_syscall, // __NR_set_thread_area	243
    allow_syscall, // __NR_get_thread_area	244
    allow_syscall, // __NR_io_setup		245
    allow_syscall, // __NR_io_destroy		246
    allow_syscall, // __NR_io_getevents	247
    allow_syscall, // __NR_io_submit		248
    allow_syscall, // __NR_io_cancel		249
    allow_syscall, // __NR_fadvise64		250
    deny_syscall,  // 251 is unused, but we need an entry for it in our table
    allow_syscall, // __NR_exit_group		252
    allow_syscall, // __NR_lookup_dcookie	253
    allow_syscall, // __NR_epoll_create	254
    allow_syscall, // __NR_epoll_ctl		255
    allow_syscall, // __NR_epoll_wait		256
    allow_syscall, // __NR_remap_file_pages	257
    allow_syscall, // __NR_set_tid_address	258
    allow_syscall, // __NR_timer_create	259
    allow_syscall, // __NR_timer_settime	(__NR_timer_create+1)
    allow_syscall, // __NR_timer_gettime	(__NR_timer_create+2)
    allow_syscall, // __NR_timer_getoverrun	(__NR_timer_create+3)
    allow_syscall, // __NR_timer_delete	(__NR_timer_create+4)
    allow_syscall, // __NR_clock_settime	(__NR_timer_create+5)
    allow_syscall, // __NR_clock_gettime	(__NR_timer_create+6)
    allow_syscall, // __NR_clock_getres	(__NR_timer_create+7)
    allow_syscall, // __NR_clock_nanosleep	(__NR_timer_create+8)
    allow_syscall, // __NR_statfs64		268
    allow_syscall, // __NR_fstatfs64		269
    allow_syscall, // __NR_tgkill		270
    allow_syscall, // __NR_utimes		271
    allow_syscall, // __NR_fadvise64_64	272
    allow_syscall, // __NR_vserver		273
    allow_syscall, // __NR_mbind		274
    allow_syscall, // __NR_get_mempolicy	275
    allow_syscall, // __NR_set_mempolicy	276
    allow_syscall, // __NR_mq_open 		277
    allow_syscall, // __NR_mq_unlink		(__NR_mq_open+1)
    allow_syscall, // __NR_mq_timedsend	(__NR_mq_open+2)
    allow_syscall, // __NR_mq_timedreceive	(__NR_mq_open+3)
    allow_syscall, // __NR_mq_notify		(__NR_mq_open+4)
    allow_syscall, // __NR_mq_getsetattr	(__NR_mq_open+5)
    allow_syscall, // __NR_kexec_load		283
    allow_syscall, // __NR_waitid		284
    deny_syscall, // __NR_sys_setaltroot	285
    allow_syscall, // __NR_add_key		286
    allow_syscall, // __NR_request_key	287
    allow_syscall, // __NR_keyctl		288
    allow_syscall, // __NR_ioprio_set		289
    allow_syscall, // __NR_ioprio_get		290
    allow_syscall, // __NR_inotify_init	291
    allow_syscall, // __NR_inotify_add_watch	292
    allow_syscall, // __NR_inotify_rm_watch	293
    allow_syscall, // __NR_migrate_pages	294
    check_openat_syscall, // __NR_openat		295
    allow_syscall, // __NR_mkdirat		296
    allow_syscall, // __NR_mknodat		297
    allow_syscall, // __NR_fchownat		298
    allow_syscall, // __NR_futimesat		299
    allow_syscall, // __NR_fstatat64		300
    allow_syscall, // __NR_unlinkat		301
    allow_syscall, // __NR_renameat		302
    allow_syscall, // __NR_linkat		303
    allow_syscall, // __NR_symlinkat		304
    allow_syscall, // __NR_readlinkat		305
    allow_syscall, // __NR_fchmodat		306
    allow_syscall, // __NR_faccessat		307
    allow_syscall, // __NR_pselect6		308
    allow_syscall, // __NR_ppoll		309
    allow_syscall, // __NR_unshare		310
    allow_syscall, // __NR_set_robust_list	311
    allow_syscall, // __NR_get_robust_list	312
    allow_syscall, // __NR_splice		313
    allow_syscall, // __NR_sync_file_range	314
    allow_syscall, // __NR_tee		315
    allow_syscall, // __NR_vmsplice		316
    allow_syscall, // __NR_move_pages		317
    allow_syscall, // __NR_getcpu		318
    allow_syscall, // __NR_epoll_pwait	319
    allow_syscall, // __NR_utimensat		320
    allow_syscall, // __NR_signalfd		321
    allow_syscall, // __NR_timerfd_create	322
    allow_syscall, // __NR_eventfd		323
    allow_syscall, // __NR_fallocate		324
    allow_syscall, // __NR_timerfd_settime	325
    allow_syscall, // __NR_timerfd_gettime	326
    allow_syscall, // __NR_signalfd4		327
    allow_syscall, // __NR_eventfd2		328
    allow_syscall, // __NR_epoll_create1	329
    allow_syscall, // __NR_dup3		330
    allow_syscall, // __NR_pipe2		331
    allow_syscall // __NR_inotify_init1	332
};
